ktor {
    application {
        modules = [
            com.bookvault.MainKt.module,
            com.bookvault.plugins.HttpKt.configureHttp,
            com.bookvault.plugins.SerializationKt.configureSerialization,
            com.bookvault.routes.RoutingKt.configureRouting
        ]
    }
    deployment {
        port = 8080
    }
}

jwt {
    secret = "local-dev-secret"
    secret = ${?JWT_SECRET}

    issuer = "bookvault"
    issuer = ${?JWT_ISSUER}

    audience = "bookvault-users"
    audience = ${?JWT_AUDIENCE}
}

database {
    url = "jdbc:postgresql://localhost:5432/postgres"
    url = ${?DB_URL}

    user = "postgres"
    user = ${?DB_USER}

    password = "postgres"
    password = ${?DB_PASSWORD}
}
